plugins {
    id 'base'
}

allprojects {
    group = rootProject.mod_group_id
    version = rootProject.mod_version

    repositories {
        mavenLocal()
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }
}

tasks.named('build') {
    dependsOn ':core:build', ':core:verifyCoreArchitecture', ':common:build', ':common:verifySharedLoaderBoundary',
            ':fabric:build', ':fabric:verifyFabricJar',
            ':neoforge:build', ':neoforge:verifyNeoForgeJar'
}
